#! /bin/bash

tmux new-window
tmux send-keys 'cd ~/work/l' 'C-m'

tmux split-window -v -p 30
tmux send-keys 'cd ~/work/hopper-functions' 'C-m'

# 最初のペインに戻る
tmux select-pane -t 0

# hopper-function
tmux split-window -h
tmux send-keys 'cd ~/work/hopper-functions' 'C-m'
tmux send-keys 'npm run start' 'C-m'

# ngrok
tmux split-window -h
tmux send-keys 'cd ~/work/hopper-functions' 'C-m'
tmux send-keys 'ngrok http -hostname=icer7.jp.ngrok.io --region jp 7071' 'C-m'

# 最初に下に分割したペインに移動
tmux select-pane -t 3

# hopper
tmux split-window -h
tmux send-keys 'cd ~/work/hopper' 'C-m'
tmux send-keys 'postgres -D /usr/local/var/postgresql@11 &' 'C-m'
tmux send-keys 'docker-compose -d' 'C-m'
tmux send-keys 'foreman start' 'C-m'

